# Generated by Django 3.2.22 on 2024-02-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
