# Generated by Django 3.2.22 on 2024-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0003_hospital_table_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_table',
            name='health_id',
            field=models.CharField(default='1000', max_length=10),
            preserve_default=False,
        ),
    ]
