# Generated by Django 3.2.22 on 2024-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0004_patient_table_health_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_table',
            name='otp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
