# Generated by Django 3.2.22 on 2024-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0005_appointment_table_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_table',
            name='district',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
