# Generated by Django 5.0.3 on 2024-04-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0006_hospital_table_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record_table',
            name='duration',
        ),
    ]
