# Generated by Django 5.0.3 on 2024-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data_app', '0007_remove_medical_record_table_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record_table',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
